In [75]:
import pandas as pd

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[4, 5, 6, 7])


## printing two dataframes
print(df, "\n\n", df1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [76]:
res = pd.concat([df,df1]) ## simple concatenation of two dataframes

res

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [77]:
import pandas as pd

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]}

data2 = {'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification  Mobile No
0     Jai   27     Nagpur           Msc         97
1  Princi   24     Kanpur            MA         91
2  Gaurav   22  Allahabad           MCA         58
3    Anuj   32    Kannuaj           Phd         76

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
3    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000

### axis

axis 0 → move down (rows)
axis 1 → move across (columns)

In [78]:
res1 = pd.concat([df,df1], axis = 1, join = 'inner') ## simple concatenation of two dataframes

res1

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
2,Gaurav,22,Allahabad,MCA,58,Gaurav,22,Allahabad,MCA,1000
3,Anuj,32,Kannuaj,Phd,76,Anuj,32,Kannuaj,Phd,2000

In [79]:
res2 = pd.concat([df,df1], axis = 0) ## simple concatenation of two dataframes

res2

     Name  Age    Address Qualification  Mobile No  Salary
0     Jai   27     Nagpur           Msc       97.0     NaN
1  Princi   24     Kanpur            MA       91.0     NaN
2  Gaurav   22  Allahabad           MCA       58.0     NaN
3    Anuj   32    Kannuaj           Phd       76.0     NaN
2  Gaurav   22  Allahabad           MCA        NaN  1000.0
3    Anuj   32    Kannuaj           Phd        NaN  2000.0
6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [80]:
res3 = pd.concat([df,df1], keys = ['x','y'])

res3

       Name  Age    Address Qualification  Mobile No  Salary
x 0     Jai   27     Nagpur           Msc       97.0     NaN
  1  Princi   24     Kanpur            MA       91.0     NaN
  2  Gaurav   22  Allahabad           MCA       58.0     NaN
  3    Anuj   32    Kannuaj           Phd       76.0     NaN
y 2  Gaurav   22  Allahabad           MCA        NaN  1000.0
  3    Anuj   32    Kannuaj           Phd        NaN  2000.0
  6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
  7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

### Concatenating Mixed DataFrames and Series

In [81]:
import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df = pd.DataFrame(data1,index=[0, 1, 2, 3])

s1 = pd.Series([1000, 2000, 3000, 4000], name='Salary')

print(df, "\n\n", s1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

 0    1000
1    2000
2    3000
3    4000
Name: Salary, dtype: int64

In [82]:
res4 = pd.concat([df,s1], axis = 1)

res4

     Name  Age    Address Qualification  Salary
0     Jai   27     Nagpur           Msc    1000
1  Princi   24     Kanpur            MA    2000
2  Gaurav   22  Allahabad           MCA    3000
3    Anuj   32    Kannuaj           Phd    4000

### Joining DataFrames Using the "on" Argument

In [83]:
import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Key':['K0', 'K1', 'K2', 'K3']}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])


print(df, "\n\n", df1)

res5 = df.join(df1, on='Key')

res5

     Name  Age Key
0     Jai   27  K0
1  Princi   24  K1
2  Gaurav   22  K2
3    Anuj   32  K3

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

     Name  Age Key    Address Qualification
0     Jai   27  K0  Allahabad           MCA
1  Princi   24  K1        NaN           NaN
2  Gaurav   22  K2    Kannuaj           Phd
3    Anuj   32  K3  Allahabad          Bcom

### Merging DataFrames Using the how Argument

| Merge Method | Join Name         | Description                              |
|--------------|------------------|------------------------------------------|
| left         | LEFT OUTER JOIN  | Use keys from left frame only            |
| right        | RIGHT OUTER JOIN | Use keys from right frame only           |
| outer        | FULL OUTER JOIN  | Use union of keys from both frames       |
| inner        | INNER JOIN       | Use intersection of keys from both frames|

In [84]:
import pandas as pd

data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)


print(df, "\n\n", df1)

res = pd.merge(df, df1, how='outer', on=['key', 'key1'])

res

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons

  key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur           B.A
2  K1   K1  Princi  24.0        NaN           NaN
3  K2   K0  Gaurav  22.0  Allahabad          Bcom
4  K3   K0     NaN   NaN    Kannuaj        B.hons
5  K3   K1    Anuj  32.0        NaN           NaN